[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "te2"
version = "0.2.133"
description = "TE2 framework runtime and tooling"
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["dependencies"]

[project.scripts]
te2 = "app.cli.run_framework:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"app" = [
    "static/**/*",
    "apps/**/*",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]
namespaces = true

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
