# pyright: strict
from __future__ import annotations

from typing import Protocol


class EditorLike(Protocol):
    value: str
    _cached_content: str
    show_minimap: bool

    def run_method(self, method_name: str, *args: object) -> object: ...
    def set_value(self, value: str) -> None: ...
    def set_language(self, language: str) -> None: ...
    def update(self) -> None: ...
    def set_diff_decorations(self, hunks: list[object]) -> None: ...
    def set_zebra_stripes(self, enabled: object) -> None: ...
    def set_font_scale(self, value: float) -> None: ...
    def set_indent_guides(self, enabled: object) -> None: ...
    def toggle_color_picker(self, enabled: object) -> None: ...
    def set_read_only(self, enabled: object) -> None: ...
    def set_sticky_scroll(self, enabled: object) -> None: ...
    def set_line_wrapping(self, enabled: bool) -> None: ...
    def set_theme(self, theme: str) -> None: ...
    def set_minimap_mode(self, mode: str) -> None: ...
    def jump_to_line(
        self,
        line: int,
        column: int = 1,
        *,
        focus: bool | None = None,
        scroll_to_top: bool | None = None,
        scroll_y: str | None = None,
    ) -> None: ...
    def open_search_panel(self) -> None: ...
    def disconnect_lsp(self) -> None: ...
    def connect_lsp(self, payload: dict[str, object]) -> None: ...
    def notify_parent(self, event_name: str, payload: dict[str, object]) -> None: ...
